### Настройки DevSecOps ###
### Общая информация о команде ###
team:
  - {
      # код команды в МУСе
      mus_code: "SNCDSO",
      # название команды в МУСе
      mus_name: "SNCDSO team",
      mus_po_mail: "RYuKhakhilev@sber.ru",
    }
    
### Общая информация о приложении ###dd
app:
  # конфигурационный элемент КЭ приложения / модуля ПО в Service Manager
  sm_id: "2720477"
  # название КЭ приложения / модуля ПО в Service Manager
  sm_name: "Ai Платформа УМиИД (AiPlatformUmiid)"
### Настройки SAST Checkmarx ###
sast_cx:
  # сredentials id в Jenkins для учетной записи Checkmarx одной команды, под которой будет проводиться сканирование
  creds_id: "ChCredsUMIID"
  # проектная область в JIRA для заведения и синхронизации дефектов
  jira_area: "AIPSN"
  # маски файлов и директорий для включения (**/*) в скан и исключения (!**/*) из скана. Пример: "!**/utils/**/*.xml" - исключение всех xml файлов в папке utils
  masks: ""
  # id профиля сканирования, по умолчанию 36. 14 - для мобильного приложения. 100003 - Smoke
  preset_id: "36"
  # макс время ожидания статуса QG в минутах
  wait_qg: "2"
  ###